---
title: Reflections on rstudio::conf 2018
author: Monica Gerber
date: '2018-04-05'
slug: reflections-on-rstudio-conf-2018
categories:
  - conferences
tags:
  - rstudio::conf
---

It's been a couple of months since [rstudio::conf 2018](https://www.rstudio.com/conference/) and I'm still mulling over what I learned in 2 days in San Diego. I grew up in the sunshine of San Diego, so it was good to be back and also feel inspired by the amazing energy of the R community. Here's a reflection on what the conference was like, what ideas I've been running with, and how what I learned will change what I do over the course of the next year.

## 1. I can contribute, no matter how small

My biggest take-away from the conference is that the reason why R is awesome is that anyone can contribute to the community, and many leaders in the R community care about the diversity of the community. This was reflected in the many talks aimed at helping people contribute to R packages, teach R, and publicize their work. 

If there is something that frustrates you about a certain task or package in R, you don't have to sit around and wish for somebody at the corporate headquarters to make it better, you can find a way to immediately contribute to a solution. It doesn't have to be a elegant or permanent solution, but taking a first try at solving the problem will get others interested and start the conversation. There are many tools from [blogdown](https://bookdown.org/yihui/blogdown/) to the [RStudio Community](https://community.rstudio.com/) to the [usethis](http://usethis.r-lib.org/) package to make getting your ideas out there easier. 

One of my favorite examples of this was Andrew Bray's talk on the [infer package](https://infer.netlify.com/). One of people's complaints about R is that there is no standard way of setting up a statistical test in R. The goal of the infer package is to perform statistical inference in a way that is intuitive and logically consistent with the tidyverse. From the talk, it sounds like the infer developers would be happy to hear from prospective contributors to the package.


Talks to watch:

* [Contributing to tidyverse packages](https://www.rstudio.com/resources/videos/contributing-to-tidyverse-packages/) by Mara Averick
* [Fireside chat with Rstudio](https://www.rstudio.com/resources/videos/fireside-chat-with-rstudio-tidyverse-discussion/)
* [You can make a package in 20 minutes](https://www.rstudio.com/resources/videos/you-can-make-a-package-in-20-minutes/) by Jim Hester
* [infer: a package for tidy statistical inference](https://www.rstudio.com/resources/videos/infer-a-package-for-tidy-statistical-inference) by Andrew Bray


## 2. R makes my job a whole lot more fun

When I first started learning R when I was in grad school, another student sent me [this comic](https://www.facebook.com/photo.php?fbid=10153987792145791&set=a.10150155755935791.338654.617055790&type=3&theater) with the message "hope it's going well for you." Apparently this comic was originally about a video game, but people seem to think it accurately describes learning R as well. At the the time I didn't know anyone who was using R and I abandoned learning it in favor of the program used in my biostatistics department. Later, when in my first job post-grad school, I dove back into R as a way to save myself from some of the frustrations I had working in that role.

At Rstudio::conf this was a theme that seemed to resonate with a lot of people: R was a way to make their jobs more enlivening and joyful and a way to innovate in their fields. Sure, the learning curve might be a bit steep, but arguably with the tidyverse packages, this is less of a concern. Students can go from install to plotting in ggplot2 in no time. And in the biostatistics of epidemiology field, R can help us think more rigorously about the methods we're using. For me, the biggest plus of using R is that I'm constantly learning something new and improving my workflow, and that's what makes me happy.

Talks to watch:

* [Five packages in five weeks--from boredom to contribution via blogging](https://www.rstudio.com/resources/videos/five-packages-in-five-weeks-from-boredom-to-contribution-via-blogging/) by Giora Simchoni, author of the [Sex, Drugs and Data](http://giorasimchoni.com/) blog
* [A SAS-to-R success story](https://www.rstudio.com/resources/videos/a-sas-to-r-success-story/) by Elizabeth J. Atkinson 
* [Accelerating cancer research with R](https://www.rstudio.com/resources/videos/accelerating-cancer-research-with-r/) by Sandra Griffith


## 3. I'm a biostatistician, but I can learn a lot from other fields

Rstudio::conf was the first non-academic conference that I went to, and the plus of going to the conference was that there were data scientists from many different backgrounds and industries to learn from. Sometimes, when I talk to someone from someone from, say, a political science background, I realize that they have a different 'language' for talking about methods. At first, this can be frustrating, but then I realized that approaching something from a different mindset can lead me to a solution I wouldn't have found otherwise.

The conference was a jumping off point for me to learn about how others are using R and structuring their workflows. There are many R users blogging about how they're using R for fun or at work. Setting up an RSS feed for all of these blogs provides endless inspiration for both my work and fun side projects.

One example of this is how data scientists can use agile development, a well-established practice in modern software development. As a team of 1, this has drastically changed how I approach my work, and could be the focus of a whole other post (or series of posts). Luckily, Elaine McVey wrote a couple of posts on her [blog](http://www.datawoman.com/) about this and spoke about it at the conference.

Talks to watch:

* [Agile data science](https://www.rstudio.com/resources/videos/agile-data-science/) by Elaine McVey
* [Differentiating by data science](https://www.rstudio.com/resources/videos/differentiating-by-data-science/) by Eric Colson
* [Imagine Boston 2030: Using R-Shiny to keep ourselves accountable and empower the public](https://www.rstudio.com/resources/videos/imagine-boston-2030-using-r-shiny-to-keep-ourselves-accountable-and-empower-the-public/) by Kayla Patel


## 4. I'm inspired to work with my local R user groups

Above I mentioned that I'm a team of 1, and this could make it is easy to get stuck in a certain way of doing things. Since no one else in my office is using R, my colleagues might not appreciate the fact that I finally figured out how `facet_grid()` can improve my `ggplot2` creations. Luckily, there was a strong presence of [Rladies](https://rladies.org/) at rstudio::conf, which inspired me to do some organizing for my local Boston chapter. Finding these networks is incredibly important to me!

It also helped me think more about how to reach out to other R users at my institution, many of whom may be 'siloed' in their academic departments. Luckily, we have an organizational GitLab account, which is the perfect place to post resources for organization-specific information about R, such as how to use R's database tools to connect to data resources. 

Here are some communities I've found out about recently:

* [R-Ladies Global](https://rladies.org/) and [R-Ladies Boston](https://www.meetup.com/rladies-boston/)
* [rOpenSci](https://ropensci.org/)
* [Data Carpentry](http://www.datacarpentry.org/)
* [The R Epidemics Consortium](https://www.repidemicsconsortium.org/)


## 5. I am still catching up on Rstudio::conf 2018

Hadley Wickham told us at the beginning of the conference that they purposely designed it so that we would have a really hard time picking which talks to attend. Luckily, many of the talks are [posted](https://www.rstudio.com/resources/videos/rstudioconf-2018-talks/) on the Rstudio website, so I can catch up on the ones I missed!


***

Thanks for reading, and see you on the internet!